version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "⬆️ "
    reviewers:
      - "LiamMacP"
    labels:
      - "dependencies"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "⬆️ "
    reviewers:
      - "LiamMacP"
    labels:
      - "dependencies"